version: '3'
services:
  database:
    image: mongo
    container_name: customer-database-container
    environment:
      - MONGO_INITDB_DATABASE=customers
    ports:
      - "27017:27017"
    volumes:
      - "mongodb:/data/db"
    networks:
      - network_m

volumes:
  mongodb:

networks:
  network_m: