name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Customer API
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: env GOOS=linux GOARCH=amd64 go build -ldflags "-extldflags '-static'" -o app ./cmd/main.go

    - name: Test
      run: go test -race -v $(go list ./... | grep -v /vendor/) -coverprofile coverage.out; go tool cover -func coverage.out

